CREATE TABLE IF NOT EXISTS public.packingordertrans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_num TEXT NOT NULL,
  part TEXT NOT NULL,
  cartonLot TEXT NOT NULL,
  startpallet INTEGER,
  endpallet INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.packingordertrans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable all for authenticated" ON public.packingordertrans
  FOR ALL USING (auth.role() = 'authenticated');
